### PR TITLE
Add support for the socklist template

### PR DESCRIPTION
**Pull request by Dreamy-Jazz**
Add support for the socklist template. See https://en.wikipedia.org/wiki/Template_talk:SPI_report#Proposed_change_to_sock_list

### CODE REVIEW

**Comment by TamzinHadasa** [comment]
Not that I can see this mattering, but if I'm following the logic correctly here, I believe it would take an empty parameter name as equivalent to a numbered one due to the `\d*` in L764. E.g. in `{{sock list|=foo}}`, it would take `foo` as a sock, while the template would throw that out.

**Comment by Dreamy-Jazz** [comment]
Good point. I will update that regex.

**Comment by Dreamy-Jazz** [comment]
If possible, this would be good for this patch to be pushed to main soon as this template is likely to be added to twinkle + the SPI preload form, and without this patch (or another similar one) the tool won't be able to read the users / IPs from the template.

**Comment by TamzinHadasa** [comment]
@Dreamy-Jazz I just realized this also needs to be used on renames. I've modified the module so that it will have the same behavior to add the master as the 1st param to `{{sock list}}` and set `note1` to `({{clerknote}} original case name)`. As a bonus, if you pass the `remove_master` param, you can avoid all that regex to actually remove the master from the wikitext. `{{sock list|Foo|Bar|remove_master=yes}}` on SPI/Foo will have the same effect as `{{sock list|Bar}}`.

**Pull request merged**
